apps/MoA/urls.py
from django.conf.urls import url

from . import views

app_name = 'MoA'

urlpatterns = [
    url(r'^Home/$', views.Home, name='Home'),
    url(r'^CreateGame/$', views.CreateGame, name='CreateGame'),
    url(r'^RecoverPlayer/$', views.RecoverPlayer, name='RecoverPlayer'),
    url(r'^SetupGame/$', views.SetupGame, name='SetupGame'),
    url(r'^SetPlayerName/$', views.SetPlayerName, name='SetPlayerName'),
    url(r'^GetConnectedPlayerColors/$', views.GetConnectedPlayerColors, name='GetConnectedPlayerColors'),
    url(r'^IamAlive/$', views.IamAlive, name='IamAlive'),
    url(r'^GetAlivePlayerColors/$', views.GetAlivePlayerColors, name='GetAlivePlayerColors'),
    url(r'^ImAliveGetAlive/$', views.ImAliveGetAlive, name='ImAliveGetAlive'),
    url(r'^GameMoA/$', views.GameMoA, name='GameMoA'),
    url(r'^GetNextPlay/$', views.GetNextPlay, name='GetNextPlay'),
    url(r'^SetNextPlayer/$', views.SetNextPlayer, name='SetNextPlayer'),
    url(r'^CheckGenuine/$', views.CheckGenuine, name='CheckGenuine'),
    url(r'^StartBB/$', views.StartBB, name='StartBB'),
    url(r'^EndGame/$', views.EndGame, name='EndGame'),
    url(r'^TestGameMoA/$', views.TestGameMoA, name='TestGameMoA'),
]

configuration/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from core.views import index

urlpatterns = [
    url(r'^$', index, name='home'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    # url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    # url(r'^MoA/', include('apps.MoA.urls', namespace='MoA')),
    url(r'^GameMaster/', include('apps.GameMaster.urls', namespace='GameMaster')),
    url(r'^Helper/', include('apps.Helper.urls', namespace='Helper')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
                          url(r'^__debug__/', include(debug_toolbar.urls)),
                      ] + urlpatterns

apps/MoA/models.py
from django.db import models
from django.utils import timezone
from django.utils.safestring import mark_safe

from .base_model import SlugMixin, AuditMixin
from .base_model import CHARACTOR_CHOICES, COLOR_CHOICES, ZODIAC_CHOICES, ZODIAC_STATUS_CHOICES

from datetime import timedelta
import os
import logging
logger = logging.getLogger(__name__)

from django.conf.locale.en import formats as en_formats
en_formats.DATETIME_FORMAT = "r"
en_formats.DATE_FORMAT = "d M Y"
en_formats.TIME_FORMAT = "H:i:s"


# Create your models here.
class Game(AuditMixin, models.Model):
	class Meta:
		# 	verbose_name = '玩家'
		# 	verbose_name_plural = '玩家'
		ordering = ['-created_at',]

	room_id = models.PositiveSmallIntegerField(
		unique=True, help_text="Room Number", verbose_name='Room ID')
	stage = models.PositiveSmallIntegerField(default=-1)
	start_color_index = models.PositiveSmallIntegerField(null=True)
	characters = models.ManyToManyField('Character', blank=True)

	def __str__(self):
		return 'Room Number: %s  Stage: %s' % (self.room_id, self.stage)


class ZodiacImage(SlugMixin, AuditMixin, models.Model):
	name = models.CharField(max_length=31, choices=ZODIAC_CHOICES, unique=True)
	image = models.FileField(upload_to='Images/', blank=True, null=True)

	def __str__(self):
		return 'Name: %s  ImagePath: %s' % (self.name, self.image)

	def get_image_name(self):
		return os.path.basename(self.image.name)

	def image_tag(self):
		return mark_safe(u'<img src="%s" />' % self.image.url)
	image_tag.short_description = 'Image'
	image_tag.allow_tags = True


class Zodiac(SlugMixin, AuditMixin, models.Model):
	name = models.CharField(max_length=31, choices=ZODIAC_CHOICES)
	genuine = models.BooleanField(default=True, verbose_name='真伪')
	sequence = models.PositiveSmallIntegerField(null=True)
	status = models.PositiveSmallIntegerField(choices=ZODIAC_STATUS_CHOICES, default=0)
	zodiac_image = models.ForeignKey(ZodiacImage, models.PROTECT, related_name='zodiacs', verbose_name='Zodiac Image')
	game = models.ForeignKey(Game, models.CASCADE, related_name='zodiacs')

	def __str__(self):
		return 'Room Number: %s  Name: %s  Genuine: %s  Sequence: %s' % (self.game.room_id, self.name, self.genuine, self.sequence)

	class Meta:
		# 	verbose_name = '玩家'
		# 	verbose_name_plural = '玩家'
		ordering = ['sequence']


class Character(SlugMixin, AuditMixin, models.Model):
	name = models.CharField(
		max_length=31, choices=CHARACTOR_CHOICES, unique=True)
	skill_description = models.CharField(max_length=1023, null=True)

	def __str__(self):
		return self.get_name_display()


class Player(SlugMixin, AuditMixin, models.Model):
	class Meta:
		# 	verbose_name = '玩家'
		# 	verbose_name_plural = '玩家'
		unique_together = (('game', 'color'), ('game', 'character'))
		ordering = ['game', 'color']

	name = models.CharField(max_length=255)
	player_code = models.PositiveSmallIntegerField(unique=True, help_text="Player Code", verbose_name='Player Code')
	color = models.CharField(max_length=7, choices=COLOR_CHOICES, null=True)
	sequence = models.PositiveSmallIntegerField(default=999)
	step = models.PositiveSmallIntegerField(default=0)
	game = models.ForeignKey(Game, models.CASCADE, related_name='players')
	character = models.ForeignKey(Character, models.PROTECT, verbose_name='Character')

	def is_alive(self):
		return self.modified_at >= timezone.now() - timedelta(seconds=8)
		
	is_alive.boolean = True
	is_alive.short_description = 'Is Alive?'


class PlayerAction(AuditMixin, models.Model):		
	skill_used = models.BooleanField(null=True)
	game = models.ForeignKey(Game, models.PROTECT, related_name='actions')
	player = models.ForeignKey(Player, models.PROTECT, related_name='actions')
	zodic = models.ForeignKey(Zodiac, models.PROTECT, related_name='actions')
	character = models.ForeignKey(Character, models.PROTECT, related_name='actions')

apps/MoA/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect
from django.utils import timezone
from django.core import serializers

from .models import Game, ZodiacImage, Zodiac, Character, Player
from .base_model import CHARACTOR_CHOICES, COLOR_CHOICES, ZODIAC_CHOICES

from datetime import timedelta
import random
import json


def get_a_character(game):
	characters = game.characters.all()
	# character = random.choice(characters)
	character = characters.first()	# for testing
	game.characters.remove(character)
	return character


def get_all_colors():
	all_colors = sorted([color[0] for color in COLOR_CHOICES])
	# print(all_colors)
	return all_colors


# Create your views here.
def Home(request):
	return render(request, 'home.html', {})


def CreateGame(request):
	room_id = random.randint(10000, 32767)
	while Game.objects.filter(room_id=room_id).count() > 0:
		room_id = random.randint(10000, 32767)	
	new_game = Game(room_id=room_id, start_color_index=random.randint(0, 7))
	new_game.save()
	zodiac_names = [zodiac[0] for zodiac in ZODIAC_CHOICES]
	# zodiac_genuines = [True] * 6 + [False] * 6
	for i in range(12):
		if i % 4 == 0:
			zodiac_genuines = [True] * 2 + [False] * 2
		name = random.choice(zodiac_names)
		zodiac_image = ZodiacImage.objects.get(name=name)
		genuine = random.choice(zodiac_genuines)
		zodiac = Zodiac(name=name, genuine=genuine, sequence=i, zodiac_image=zodiac_image, game=new_game)
		zodiac.save()
		print(zodiac)
		new_game.zodiacs.add(zodiac)
		zodiac_names.remove(name)
		zodiac_genuines.remove(genuine)
	request.session['create_at'] = str(timezone.now())
	characters = Character.objects.all()
	for character in characters:
		new_game.characters.add(character)
	return render(request, 'to_setup.html', {'room_id': room_id})


def RecoverPlayer(request):
	player_code = request.POST.get('player_code', None)
	if player_code is None or len(player_code) != 3:
		return redirect('MoA:Home')
	player = Player.objects.filter(player_code=player_code).first()
	if player is None:
		return redirect('MoA:Home')

	request.session['player_code'] = player_code
	room_id = player.game.room_id
	game = Game.objects.filter(room_id=room_id).first()
	if game is None:
		return redirect('MoA:Home')
	if game.stage == -1:
		return render(request, 'to_setup.html', {'room_id': room_id})
	else:
		return render(request, 'to_game.html', {'room_id': room_id})


def SetupGame(request):
	room_id = request.POST.get('room_id', None)
	if room_id is None or len(room_id) != 5:
		return redirect('MoA:Home')
	game = Game.objects.filter(room_id=room_id).first()
	if game is None:
		return redirect('MoA:Home')

	player_code = request.session.get('player_code', None)
	print(player_code)

	all_colors = get_all_colors()
	if player_code is None:
		player_code = random.randint(100, 999)
		while Player.objects.filter(player_code=player_code).count() > 0:
			player_code = random.randint(100, 999)
		request.session['player_code'] = player_code
		request.session['join_at'] = str(timezone.now())
		character = get_a_character(game)
		players = game.players.all()
		player_colors = [player.color for player in players]
		available_colors = [c for c in player_colors + all_colors if c not in player_colors or c not in all_colors]
		# color = random.choice(available_colors)
		color = available_colors[0]	# for testing
		new_player = Player(player_code=player_code, color=color, game=game, character=character)
		name = new_player.get_color_display()
		new_player.name = name
		new_player.save()
		game.players.add(new_player)
	player = Player.objects.get(player_code=player_code)
	return render(request, 'setup.html', {'room_id': room_id, 'player': player, 'colors': all_colors})


def SetPlayerName(request):
	player_code = request.session.get('player_code', None)
	player = Player.objects.get(player_code=player_code)
	player.name = request.POST.get('name', None)
	player.save()
	return HttpResponse(name, status=201)


def GetConnectedPlayerColors(request):
	room_id = request.POST.get('room_id', None)
	game = Game.objects.get(room_id=room_id)
	players = game.players.all()
	player_colors = [player.color for player in players]
	return HttpResponse(json.dumps(player_colors), content_type='application/json', status=200)


def IamAlive(request):
	player_code = request.POST.get('player_code', None)
	player = Player.objects.get(player_code=player_code)
	player.save()
	return HttpResponse('alive', status=200)


def GetAlivePlayerColors(request):
	room_id = request.POST.get('room_id', None)
	game = Game.objects.get(room_id=room_id)
	if game.stage == -1:
		players = [player for player in game.players.all() if player.is_alive()]
	elif game.stage >= 0:
		players = game.players.all()
	player_colors = [player.color for player in players]
	return HttpResponse(json.dumps(player_colors), content_type='application/json', status=200)


def ImAliveGetAlive(request):
	player_code = request.POST.get('player_code', None)
	player = Player.objects.get(player_code=player_code)
	player.save()
	room_id = request.POST.get('room_id', None)
	game = Game.objects.get(room_id=room_id)
	if game.stage == -1:
		players = [player for player in game.players.all() if player.is_alive()]
	elif game.stage >= 0:
		players = game.players.all()
	player_colors = [player.color for player in players]
	return HttpResponse(json.dumps(player_colors), content_type='application/json', status=200)


def GameMoA(request):
	room_id = request.POST.get('room_id', None)
	if room_id is None:
		return redirect('MoA:SetupGame')

	game = Game.objects.get(room_id=room_id)
	if game.stage == -1:
		# game.stage = 0
		# To-Do: another ready check to set to 1
		game.stage = 101
		game.save()
		# all_colors = get_all_colors()
		# start_color = all_colors[game.start_color_index]
		# player = game.players.filter(color=color).first()
		player = game.players.all().first() # for testing
		player.sequence = 1
		player.save()
	player_code = request.session.get('player_code', None)
	me = Player.objects.get(player_code=player_code)
	players = game.players.all()
	return render(request, 'game.html', {'game': game, 'me': me, 'room_id': room_id, 'players': players})


def GetNextPlay(request):
	player_code = request.POST.get('player_code', None)
	room_id = request.POST.get('room_id', None)
	if player_code is None or room_id is None:
		return redirect('MoA:SetupGame')

	player = Player.objects.get(player_code=player_code)
	game = Game.objects.get(room_id=room_id)
	stage_round = int(game.stage / 100)
	if stage_round > 0 and player.sequence == game.stage % 10:
		start = stage_round - 1
		end = stage_round * 4
		# print(start, end)
		zodiacs = game.zodiacs.all()[start:end]
		ZODIACS = []
		for zodiac in zodiacs:
			ZODIACS.append({'pk': zodiac.pk, 'zodiac_image_url': zodiac.zodiac_image.image.url})
		# print(ZODIACS)
		return JsonResponse(ZODIACS, safe=False, status=201)
	elif player.sequence == game.stage % 100 / 10.0:
		return HttpResponse(serializers.serialize('json', game.players.all()), content_type='application/json', status=202)
	elif game.stage == 100:
		return HttpResponse('BB', status=203)
	else:
		return HttpResponse('wait', status=209)


def SetNextPlayer(request):
	player_code = request.POST.get('player_code', None)
	color = request.POST.get('color', None)
	if player_code is None or color is None:
		return redirect('MoA:SetupGame')

	cur_player = Player.objects.get(player_code=player_code)
	game = cur_player.game
	if cur_player.sequence == game.stage % 100 / 10.0:
		next_player = game.players.get(color=color)
		# print(next_player)
		next_player.sequence = cur_player.sequence + 1
		next_player.save()
		game.stage = game.stage - game.stage % 10 + next_player.sequence
		game.save()
	return HttpResponse()


def CheckGenuine(request):
	player_code = request.POST.get('player_code', None)
	room_id = request.POST.get('room_id', None)
	if player_code is None or room_id is None:
		return redirect('MoA:SetupGame')

	zodiac_pk = request.POST.get('zodiac_pk', None)
	if zodiac_pk is None:
		return redirect('MoA:GameMoA')

	player = Player.objects.get(player_code=player_code)
	game = Game.objects.get(room_id=room_id)
	zodiac = Zodiac.objects.get(pk=zodiac_pk)
	if player is None or game is None or zodiac is None:
		return redirect('MoA:GameMoA')

	if player.sequence != game.stage % 10:
		return redirect('MoA:GameMoA')

	game.stage = game.stage - game.stage % 100 + game.stage % 10 * 10
	game.save()
	return HttpResponse(zodiac.genuine, status=200)


def StartBB(request):
	room_id = request.POST.get('room_id', None)
	if room_id is None:
		return redirect('MoA:SetupGame')

	game = Game.objects.get(room_id=room_id)
	for player in game.players.all():
		if player.sequence > game.stage % 100 - game.stage % 10:
			return HttpResponse('not yet BB', status=209)
	game.stage = game.stage - game.stage % 100 + 99
	game.save()
	return HttpResponse('Start BB', status=200)


def EndGame(request):
	del request.session['player_code']
	# del request.session['join_at']
	# del request.session['create_at']
	return HttpResponse()


def TestGameMoA(request):
	room_id = request.POST.get('room_id', None)
	if room_id is None:
		return redirect('MoA:SetupGame')

	game = Game.objects.get(room_id=room_id)
	if game.stage == -1:
		# game.stage = 0
		# To-Do: another ready check to set to 1
		game.stage = 1
		game.save()
		all_colors = get_all_colors()
		start_color = all_colors[game.start_color_index]
		player = game.players.filter(color=color).first()
		player.sequence = 1
		player.save()
	player_code = request.session.get('player_code', None)
	me = Player.objects.get(player_code=player_code)
	return render(request, 'game.html', {'game': game, 'me': me, 'room_id': room_id})

apps/MoA/templates/setup.html
{% load static i18n %}
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Mystery of Antiques</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- <link rel="apple-touch-icon" href="apple-touch-icon.png"> -->
	<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'plugin/form-wizard/wizard.css' %}">
	<link rel="stylesheet" href="{% static 'css/radioselector.css' %}">
	<style type="text/css">
	.panel.movingIn {
		z-index: 9;
	}

	.radioMethod .fa {
		position: absolute;
		color: #4A79A3;
		padding: 1px;
		top: -10px;
		right: -10px;
		display: none;
	}

	.radioMethod.checked .fa {
		display: block !important;
		z-index: 9;
	}
	</style>
</head>

<body>
	<div class="wrapper">
		<div id="wizard" class="wizard">
			<div class="wizard__content">
				<header class="wizard__header">
					<div class="wizard__header-overlay"></div>
					<div class="wizard__header-content">
						<h1 class="wizard__title" >房间号码：{{ room_id }}</h1>
						<p class="wizard__subheading"></p>
					</div>
					<div class="wizard__steps">
						<nav class="steps">
							<div class="step">
								<div class="step__content">
									<p class="step__number"><i class="fab fa-github-alt"></i></p>
									<svg class="checkmark" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 52 52">
										<circle class="checkmark__circle" cx="26" cy="26" r="25" fill="none" />
										<path class="checkmark__check" fill="none" d="M14.1 27.2l7.1 7.2 16.7-16.8" />
									</svg>
									<div class="lines">
										<div class="line -start">
										</div>
										<div class="line -background">
										</div>
										<div class="line -progress">
										</div>
									</div>
								</div>
							</div>
							<div class="step">
								<div class="step__content">
									<p class="step__number"><i class="fas fa-book"></i></p>
									<svg class="checkmark" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 52 52">
										<circle class="checkmark__circle" cx="26" cy="26" r="25" fill="none" />
										<path class="checkmark__check" fill="none" d="M14.1 27.2l7.1 7.2 16.7-16.8" />
									</svg>
									<div class="lines">
										<div class="line -background">
										</div>
										<div class="line -progress">
										</div>
									</div>
								</div>
							</div>
							<div class="step">
								<div class="step__content">
									<p class="step__number"><i class="fab fa-angellist"></i></p>
									<svg class="checkmark" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 52 52">
										<circle class="checkmark__circle" cx="26" cy="26" r="25" fill="none" />
										<path class="checkmark__check" fill="none" d="M14.1 27.2l7.1 7.2 16.7-16.8" />
									</svg>
									<div class="lines">
										<div class="line -background">
										</div>
										<div class="line -progress">
										</div>
									</div>
								</div>
							</div>
						</nav>
					</div>
				</header>
				<div class="panels">
					<div class="panel">
						<header class="panel__header">
							<h2 class="panel__title">请输入你的名字：</h2>
							<p class="panel__subheading"></p>
						</header>
						<p class="panel__content"></p>
						<input type="text" name="name" id="name" autocomplete="off" placeholder="名字" value="{{ player.name }}">
						<button type="button" class="btn btn-success" id="btnName">确定</button>
					</div>
					<div class="panel">
						<header class="panel__header">
							<h2 class="panel__title">你的玩家ID是： <b>{{ player.player_code }}</b> </h2>
							<p class="panel__subheading"></p>
						</header>
						<p class="panel__content">请牢记！！！！！</p>
					</div>
					<div class="panel">
						<header class="panel__header">
							<h2 class="panel__title">你的角色是： <b>{{ player.character.get_name_display }}</b> </h2>
							<p class="panel__subheading"></p>
						</header>
						<p class="panel__content"><b>技能：</b>{{ player.character.skill_description }}</p>
					</div>
				</div>
				<div class="wizard__footer">
					<button class="button previous disabled">Previous</button>
					<button class="button next disabled" id="btnNext">Next</button>
				</div>
			</div>
			<h1 class="wizard__congrats-message" style="display: none;">
				<div class="radioWrap">
					<div class="btn-group radioBtnGroup btn-group-justified" data-toggle="buttons">
						{% for color in colors %}
						<label class="radioMethod" data-color="{{ color }}">
							<i class="fa fa-check hidden"></i>
							<div class="method {% if color == 'Black' %} character-white {% else %} character {% endif %}" style="background-color: {{ color }}"></div>
						</label>
						{% if forloop.counter == 4 %}
						</div>
						<div class="btn-group radioBtnGroup btn-group-justified" data-toggle="buttons">
						{% endif %}
						{% endfor %}
					</div>
				</div>
				你是{{ player.get_color_display }}色玩家！ <br /> 房间号：{{ room_id }} <br /> 玩家ID：{{ player.player_code }} <br /> 请牢记！！！
			</h1>
		</div>
	</div>
	<form id="fm" method="POST" action="{% url 'MoA:GameMoA' %}">
		{% csrf_token %}
		<input type="hidden" class="form-control-plaintext" name="room_id" value="{{ room_id }}">
	</form>
	<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/cookie.js' %}"></script>
	<script src="{% static 'plugin/form-wizard/wizard.js' %}"></script>
	<script type="text/javascript">
	function wizard_completed() {
		console.log("wizard_completed");
		$("h1[class='wizard__congrats-message']").css("display", "");
		setInterval(function() {
			$.ajaxSetup({
				beforeSend: function(xhr, settings) {
					if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
						xhr.setRequestHeader("X-CSRFToken", csrftoken);
					}
				}
			});
			$.ajax({
				url: "{% url 'MoA:ImAliveGetAlive' %}",
				type: "POST",
				data: {
					"player_code": "{{ player.player_code }}",
					"room_id": "{{ room_id }}",
				},
				success: function(result) {
					// alert(result);
					var ready_player_cout = 0;
					result.forEach(function(color) {
						$("[data-color='" + color + "']").addClass("checked");
						ready_player_cout++;
					});
					if (ready_player_cout >= 3) {
						$("#fm").submit();
					}
				},
				fail: function(result) {
					$(".radioMethod").removeClass("checked");
				}
			});
			// $.ajax({
			// 	url: "{% url 'MoA:IamAlive' %}",
			// 	type: "POST",
			// 	data: {
			// 		"player_code": "{{ player.player_code }}",
			// 	},
			// 	success: function(result) {
			// 		// alert(result);
			// 	}
			// });
			// $.ajax({
			// 	url: "{% url 'MoA:GetAlivePlayerColors' %}",
			// 	type: "POST",
			// 	data: {
			// 		"room_id": "{{ room_id }}",
			// 	},
			// 	success: function(result) {
			// 		// alert(result);
			// 		var ready_player_cout = 0;
			// 		result.forEach(function(color) {
			// 			$("[data-color='" + color + "']").addClass("checked");
			// 			ready_player_cout++;
			// 		});
			// 		if (ready_player_cout == 3) {
			// 			$("#fm").submit();
			// 		}
			// 	}
			// });
			$.ajax({
				url: "{% url 'MoA:GetConnectedPlayerColors' %}",
				type: "POST",
				data: {
					"room_id": "{{ room_id }}",
				},
				success: function(result) {
					// alert(result);
					result.forEach(function(color) {
						$("[data-color='" + color + "']").addClass("active");
					});
				},
				fail: function(result) {
					$(".radioMethod").removeClass("active");
				}
			});
		}, 5000);
	}
	$(function() {
		var wizardElement = document.getElementById("wizard");
		var wizard = new Wizard(wizardElement, wizard_completed);
		var buttonNext = document.querySelector(".next");
		var buttonPrevious = document.querySelector(".previous");
		$("#btnName").click(function() {
			$.ajax({
				url: "{% url 'MoA:SetPlayerName' %}",
				type: "POST",
				data: {
					"name": $("#name").val(),
				},
				success: function(result) {
					// alert(result);
					wizard.addControls(buttonPrevious, buttonNext);
					buttonNext.click();
					buttonNext.classList.remove("disabled");
					$("#btnName").text("修改");
					$("#name").val(result);
				}
			});
		});
		{% if player.name %}
			$("#btnNext").removeClass("disabled");
			$("#btnName").text("修改");
			wizard.addControls(buttonPrevious, buttonNext); 
		{% endif %}
	});
	</script>
</body>

</html>

apps/MoA/templates/to_game.html
{% load static i18n %}
<!DOCTYPE html>
<html>

<head>
</head>

<body>
	<form method="POST" action="{% url 'MoA:GameMoA' %}" id="fm">
		{% csrf_token %}
		<input type="hidden" class="form-control-plaintext" name="room_id" placeholder="00000" value="{{ room_id }}" required>
	</form>
	<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 'js/cookie.js' %}"></script>
	<script type="text/javascript">
	$(function() {
		$("#fm").submit();
	});
	</script>
</body>

</html>

apps/MoA/templates/to_setup.html
{% load static i18n %}
<!DOCTYPE html>
<html>

<head>
</head>

<body>
	<form method="POST" action="{% url 'MoA:SetupGame' %}" id="fm">
		{% csrf_token %}
		<input type="hidden" class="form-control-plaintext" name="room_id" placeholder="00000" value="{{ room_id }}" required>
	</form>
	<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 'js/cookie.js' %}"></script>
	<script type="text/javascript">
	$(function() {
		$("#fm").submit();
	});
	</script>
</body>

</html>