apps/Helper/urls.py
# -*- encoding: utf-8 -*-

from django.urls import path, re_path

from . import views

app_name = 'Helper'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('create_game/', views.create_game, name='create_game'),
    path('setup_game/<int:room_id>/', views.setup_game, name='setup_game'),
    path('complete_setup_game/<int:room_id>/', views.complete_setup_game, name='complete_setup_game'),
    path('game/<int:room_id>/', views.game, name='game'),
]

apps/MoA/urls.py
from django.conf.urls import url

from . import views

app_name = 'MoA'

urlpatterns = [
    url(r'^Home/$', views.Home, name='Home'),
    url(r'^CreateGame/$', views.CreateGame, name='CreateGame'),
    url(r'^RecoverPlayer/$', views.RecoverPlayer, name='RecoverPlayer'),
    url(r'^SetupGame/$', views.SetupGame, name='SetupGame'),
    url(r'^SetPlayerName/$', views.SetPlayerName, name='SetPlayerName'),
    url(r'^GetConnectedPlayerColors/$', views.GetConnectedPlayerColors, name='GetConnectedPlayerColors'),
    url(r'^IamAlive/$', views.IamAlive, name='IamAlive'),
    url(r'^GetAlivePlayerColors/$', views.GetAlivePlayerColors, name='GetAlivePlayerColors'),
    url(r'^ImAliveGetAlive/$', views.ImAliveGetAlive, name='ImAliveGetAlive'),
    url(r'^GameMoA/$', views.GameMoA, name='GameMoA'),
    url(r'^GetNextPlay/$', views.GetNextPlay, name='GetNextPlay'),
    url(r'^SetNextPlayer/$', views.SetNextPlayer, name='SetNextPlayer'),
    url(r'^CheckGenuine/$', views.CheckGenuine, name='CheckGenuine'),
    url(r'^StartBB/$', views.StartBB, name='StartBB'),
    url(r'^EndGame/$', views.EndGame, name='EndGame'),
    url(r'^TestGameMoA/$', views.TestGameMoA, name='TestGameMoA'),
]

configuration/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from core.views import index

urlpatterns = [
    url(r'^$', index, name='home'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    # url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    # url(r'^MoA/', include('apps.MoA.urls', namespace='MoA')),
    url(r'^GameMaster/', include('apps.GameMaster.urls', namespace='GameMaster')),
    url(r'^Helper/', include('apps.Helper.urls', namespace='Helper')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
                          url(r'^__debug__/', include(debug_toolbar.urls)),
                      ] + urlpatterns

apps/Helper/models.py
from django.db import models

# Create your models here.

apps/MoA/models.py
from django.db import models
from django.utils import timezone
from django.utils.safestring import mark_safe

from .base_model import SlugMixin, AuditMixin
from .base_model import CHARACTOR_CHOICES, COLOR_CHOICES, ZODIAC_CHOICES, ZODIAC_STATUS_CHOICES

from datetime import timedelta
import os
import logging
logger = logging.getLogger(__name__)

from django.conf.locale.en import formats as en_formats
en_formats.DATETIME_FORMAT = "r"
en_formats.DATE_FORMAT = "d M Y"
en_formats.TIME_FORMAT = "H:i:s"


# Create your models here.
class Game(AuditMixin, models.Model):
	class Meta:
		# 	verbose_name = '玩家'
		# 	verbose_name_plural = '玩家'
		ordering = ['-created_at',]

	room_id = models.PositiveSmallIntegerField(
		unique=True, help_text="Room Number", verbose_name='Room ID')
	stage = models.PositiveSmallIntegerField(default=-1)
	start_color_index = models.PositiveSmallIntegerField(null=True)
	characters = models.ManyToManyField('Character', blank=True)

	def __str__(self):
		return 'Room Number: %s  Stage: %s' % (self.room_id, self.stage)


class ZodiacImage(SlugMixin, AuditMixin, models.Model):
	name = models.CharField(max_length=31, choices=ZODIAC_CHOICES, unique=True)
	image = models.FileField(upload_to='Images/', blank=True, null=True)

	def __str__(self):
		return 'Name: %s  ImagePath: %s' % (self.name, self.image)

	def get_image_name(self):
		return os.path.basename(self.image.name)

	def image_tag(self):
		return mark_safe(u'<img src="%s" />' % self.image.url)
	image_tag.short_description = 'Image'
	image_tag.allow_tags = True


class Zodiac(SlugMixin, AuditMixin, models.Model):
	name = models.CharField(max_length=31, choices=ZODIAC_CHOICES)
	genuine = models.BooleanField(default=True, verbose_name='真伪')
	sequence = models.PositiveSmallIntegerField(null=True)
	status = models.PositiveSmallIntegerField(choices=ZODIAC_STATUS_CHOICES, default=0)
	zodiac_image = models.ForeignKey(ZodiacImage, models.PROTECT, related_name='zodiacs', verbose_name='Zodiac Image')
	game = models.ForeignKey(Game, models.CASCADE, related_name='zodiacs')

	def __str__(self):
		return 'Room Number: %s  Name: %s  Genuine: %s  Sequence: %s' % (self.game.room_id, self.name, self.genuine, self.sequence)

	class Meta:
		# 	verbose_name = '玩家'
		# 	verbose_name_plural = '玩家'
		ordering = ['sequence']


class Character(SlugMixin, AuditMixin, models.Model):
	name = models.CharField(
		max_length=31, choices=CHARACTOR_CHOICES, unique=True)
	skill_description = models.CharField(max_length=1023, null=True)

	def __str__(self):
		return self.get_name_display()


class Player(SlugMixin, AuditMixin, models.Model):
	class Meta:
		# 	verbose_name = '玩家'
		# 	verbose_name_plural = '玩家'
		unique_together = (('game', 'color'), ('game', 'character'))
		ordering = ['game', 'color']

	name = models.CharField(max_length=255)
	player_code = models.PositiveSmallIntegerField(unique=True, help_text="Player Code", verbose_name='Player Code')
	color = models.CharField(max_length=7, choices=COLOR_CHOICES, null=True)
	sequence = models.PositiveSmallIntegerField(default=999)
	step = models.PositiveSmallIntegerField(default=0)
	game = models.ForeignKey(Game, models.CASCADE, related_name='players')
	character = models.ForeignKey(Character, models.PROTECT, verbose_name='Character')

	def is_alive(self):
		return self.modified_at >= timezone.now() - timedelta(seconds=8)
		
	is_alive.boolean = True
	is_alive.short_description = 'Is Alive?'


class PlayerAction(AuditMixin, models.Model):		
	skill_used = models.BooleanField(null=True)
	game = models.ForeignKey(Game, models.PROTECT, related_name='actions')
	player = models.ForeignKey(Player, models.PROTECT, related_name='actions')
	zodic = models.ForeignKey(Zodiac, models.PROTECT, related_name='actions')
	character = models.ForeignKey(Character, models.PROTECT, related_name='actions')

apps/Helper/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect
from django.utils import timezone
from django.core import serializers

from apps.GameMaster.models import Game, ZodiacImage, Zodiac, Character, Player
from apps.GameMaster.constants import CHARACTOR_CHOICES, COLOR_CHOICES, ZODIAC_CHOICES

from datetime import timedelta
import random
import json

# Create your views here.
def home(request):
	return render(request, 'home.html', {})


def create_game(request):
	print('create_game')
	room_id = random.randint(10000, 32767)
	while Game.objects.filter(room_id=room_id).count() > 0:
		room_id = random.randint(10000, 32767)
	new_game = Game(room_id=room_id, start_color_index=random.randint(0, 7))
	print('new_game', new_game)
	new_game.save()
	zodiac_names = [zodiac[0] for zodiac in ZODIAC_CHOICES]
	for i in range(12):
		if i % 4 == 0:
			zodiac_genuines = [True] * 2 + [False] * 2
			print()
		name = random.choice(zodiac_names)
		zodiac_image = ZodiacImage.objects.get(name=name)
		genuine = random.choice(zodiac_genuines)
		zodiac = Zodiac(name=name, genuine=genuine, sequence=i, zodiac_image=zodiac_image, game=new_game)
		zodiac.save()
		print(zodiac)
		new_game.zodiacs.add(zodiac)
		zodiac_names.remove(name)
		zodiac_genuines.remove(genuine)
	return render(request, 'to_setup.html', {'room_id': room_id})


def setup_game(request, room_id):
	# room_id = request.POST.get('room_id', None)
	if room_id is None or len(str(room_id)) != 5:
		return redirect('Helper:home')
	game = Game.objects.filter(room_id=room_id).first()
	if game is None:
		return redirect('Helper:home')
	# print('setup_game')
	characters = []
	for character in CHARACTOR_CHOICES:
		characters.append({'value': character[0], 'name': character[1]})
	return render(request, 'setup.html', {'room_id': room_id, 'numbers_of_players': range(1, 9), 'characters': characters})


def complete_setup_game(request, room_id):
	# room_id = request.POST.get('room_id', None)
	if room_id is None or len(str(room_id)) != 5:
		return redirect('Helper:home')
	game = Game.objects.filter(room_id=room_id).first()
	if game is None:
		return redirect('Helper:home')
	print('complete_setup_game')
	players = []
	game.players.all().delete()
	for i in range(1, 9):
		player_name = request.POST.get('player_name' + str(i), None)
		character_name = request.POST.get('character_name' + str(i), None)
		player_code = random.randint(100, 999)
		while Player.objects.filter(player_code=player_code).count() > 0:
			player_code = random.randint(100, 999)
		character = Character.objects.get(name=character_name)
		player, created = Player.objects.get_or_create(name=player_name, player_code=player_code, character=character, game=game)
		players.append({'player_name': player_name, 'character_name': character_name, 'player': player})
		game.players.add(player)
	print(players)
	print(game)
	return render(request, 'to_game.html', {'room_id': room_id})


def game(request):
	room_id = request.POST.get('room_id', None)
	if room_id is None:
		return redirect('Helper:home')

	game = Game.objects.get(room_id=room_id)
	if game.stage == -1:
		# game.stage = 0
		# To-Do: another ready check to set to 1
		game.stage = 101
		# game.save()
		# all_colors = get_all_colors()
		# start_color = all_colors[game.start_color_index]
		# player = game.players.filter(color=color).first()
		player = game.players.all().first() # for testing
		# player.sequence = 1
		# player.save()
	player_code = request.session.get('player_code', None)
	me = Player.objects.get(player_code=player_code)
	players = game.players.all()
	return HttpResponse(players)
	# return render(request, 'game.html', {'game': game, 'me': me, 'room_id': room_id, 'players': players})

apps/Helper/templates/game.html
{% load static i18n %}
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Mystery of Antiques</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- <link rel="apple-touch-icon" href="apple-touch-icon.png"> -->
	<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/radioselector.css' %}">
	<style type="text/css">
	li.btn {
		margin-right: 10px;
	}

	img.js-avatar-me {
		margin: 15px 10px 15px 10px;
	}

	input[type='radio'] {
		display: none;
	}

	.dim {
		opacity: .4;
		position: absolute;
		top: 0;
		left: 0;
		width: 100%;
		height: 100%;
		z-index: 9;
		background-color: rgba(0, 0, 0, 0.3); /*dim the background*/
	}
	</style>
</head>

<body>
	<main role="main" class="container">
		你是{{ me.get_color_display }}色玩家！ <br /> 房间号：{{ room_id }} <br /> 玩家ID：{{ me.player_code }}
		<form>
			{% csrf_token %}
			<div class="form-group row">
				<div class="btn-group btn-group-toggle" data-toggle="buttons">
					<ul id="zodiac_investigate"></ul>
				</div>
			</div>
			<div id="player_sequence" class="form-group row" style="display: none;">
				<div class="radioWrap">
					<div class="btn-group radioBtnGroup btn-group-justified" data-toggle="buttons">
						{% for player in players %}
						<label class="btn radioMethod sequence {% if player.pk == me.pk %}dim{% endif %}" data-color="{{ player.color }}">
							<div class="method {% if player.color == 'Black' %} character-white {% else %} character {% endif %}" style="background-color: {{ player.color }}"></div>
							<input type="radio" name="players_sequence" {% if player.pk == me.pk %}disabled{% endif %}>
						</label>
					{% if forloop.counter == 4 %}
					</div>
					<div class="btn-group radioBtnGroup btn-group-justified" data-toggle="buttons">
					{% endif %}
					{% endfor %}
					</div>
				</div>
			</div>
		</form>
	</main>
	<form id="fm" method="POST" action="">
		{% csrf_token %}
		<input type="hidden" class="form-control-plaintext" name="room_id" value="{{ room_id }}" required>
	</form>
	<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/cookie.js' %}"></script>
	<script type="text/javascript">
	String.prototype.format = function () {
		var args = arguments;
		return this.replace(/\{(\d+)\}/g, function (m, n) { return args[n]; });
	};
	$(function() {
		setInterval(function() {
			$.ajaxSetup({
				beforeSend: function(xhr, settings) {
					if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
						xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
					}
				}
			});
			$.ajax({
				url: "{% url 'MoA:GetNextPlay' %}",
				type: "POST",
				data: {
					"player_code": "{{ me.player_code }}",
					"room_id": "{{ room_id }}",
				},
				statusCode: {
					201: function(response) {
						// console.log(response);
						if ($("#zodiac_investigate").html() == "") {
							for (let i = 0; i < 4; i++) {
								var zodiac = response[i];
								// $("#zodiac_investigate").append("");
								var $li = $("<li class='btn btn-light'></li>");
								var $input = $("<input type='radio' name='options' id='option{0}' autocomplete='off'>".format(zodiac.pk));
								var $img = $("<img src='{0}' alt='{1}' class='-avatar js-avatar-me'>".format(zodiac.zodiac_image_url, zodiac.pk));
								$li.append($input, $img);
								$("#zodiac_investigate").append($li);
							}
							$("img").click(function() {
								var zodiac_pk = $(this).attr("alt");
								console.log(zodiac_pk);
								$.ajax({
									url: "{% url 'MoA:CheckGenuine' %}",
									type: "POST",
									data: {
										"player_code": "{{ me.player_code }}",
										"room_id": "{{ room_id }}",
										"zodiac_pk": zodiac_pk,
									},
									success: function(result) {
										console.log("zodiac_investigate", result);
										if (result === "True")
											alert("真");
										if (result === "False")
											alert("伪");
										$("#zodiac_investigate").html("");
									}
								});
							})
						}
					},
					202: function(response) {
						// To-Do: dynamic generation
						// console.log(response);
						var start_speech = true;
						response.forEach(function(player) {
							if (player.fields.sequence <= {{ me.sequence }}) {
								var label = $("label[data-color={0}]".format(player.fields.color))
								label.addClass("dim");
								label.children("input").prop('disabled', true);
							}
							else {
								start_speech = false;
							}
						});
						$("#player_sequence").css("display", "");
						if (start_speech) {
							setTimeout(function() {
								$.ajax({
									url: "{% url 'MoA:StartBB' %}",
									type: "POST",
									data: {
										"room_id": "{{ room_id }}",
									},
									success: function(result) {
										// alert(result);
										$("#player_sequence").css("display", "none");
									}
								});
							}, 5000);
						}
					}
				}, success: function(result) {
					
				},
			});
		}, 3000);
		$("label.sequence").click(function() {
			// console.log($(this).data("color"));
			if (!$(this).prop('disabled')) {
				$.ajax({
					url: "{% url 'MoA:SetNextPlayer' %}",
					type: "POST",
					data: {
						"player_code": "{{ me.player_code }}",
						"color": $(this).data("color"),
					},
					success: function(result) {
						// alert(result);
						setTimeout(function() {
							$("#player_sequence").css("display", "none");
						}, 500);
					}
				});
			}
		});
	});
	</script>
</body>

</html>

apps/Helper/templates/game_test.html
{% load static i18n %}
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Mystery of Antiques</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- <link rel="apple-touch-icon" href="apple-touch-icon.png"> -->
	<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/radioselector.css' %}">
	<style type="text/css">
	img.js-avatar-me {
		margin: 15px 10px 15px 10px;
	}

	input[type='radio'] {
		display: none;
	}

	.dim {
		opacity: .4;
		position: absolute;
		top: 0;
		left: 0;
		width: 100%;
		height: 100%;
		z-index: 9;
		background-color: rgba(0, 0, 0, 0.3); /*dim the background*/
	}
	</style>
</head>

<body>
	<main role="main" class="container">
		你是{{ me.get_color_display }}色玩家！ <br /> 房间号：{{ room_id }} <br /> 玩家ID：{{ me.player_code }}
		<form>
			{% for zodiac in game.zodiacs.all %}
			{% if forloop.counter0|divisibleby:4 %}
			<div class="form-group row">
				<div class="btn-group btn-group-toggle" data-toggle="buttons">
					<ul>
			{% endif %}
						<li class="btn btn-light">
							<input type="radio" name="options" id="option{{ forloop.counter }}" autocomplete="off">
							<img src="{{ zodiac.zodiac_image.image.url }}" alt="{{ zodiac.genuine }}" class="-avatar js-avatar-me">
						</li>
			{% if forloop.counter|divisibleby:4 %}
					</ul>
				</div>
			</div>
			{% endif %}
			{% endfor %}
			<div class="form-group row">
				<label for="genuine" class="offset-sm-1 col-form-label">Check genuine:</label>
				<div class="col-sm-2">
					<input type="text" class="form-control" id="genuine">
				</div>
			</div>
			<div class="form-group row">
				{% for player in game.players.all %}
				<div class="card" style="width: 150px; margin: 0px 10px;">
					<div class="card-body">
						<label class="radioMethod">
							<div class="method {% if player.color == 'Black' %} character-white {% else %} character {% endif %}" style="background-color: {{ player.color }}"></div>
						</label>
						<h5 class="card-title" style="color: {{ player.color }};">{{ player.name }}</h5>
						{% if forloop.first and player.color == me.color %}
						<h6 class="card-subtitle mb-2 text-muted">请行动</h6>
						<!-- <p class="card-text">请选择下一位行动的玩家</p> -->
						{% else %}
						<h6 class="card-subtitle mb-2 text-muted">请等待</h6>
						{% endif %}
					</div>
				</div>
				{% endfor %}
			</div>
			<div id="player_sequence" class="form-group row" style="display: none;">
				<div class="radioWrap">
					<div class="btn-group radioBtnGroup btn-group-justified" data-toggle="buttons">
						{% for player in game.players.all %}
						<label class="btn radioMethod sequence {% if player.pk == me.pk %}dim{% endif %}" data-color="{{ player.color }}">
							<div class="method {% if player.color == 'Black' %} character-white {% else %} character {% endif %}" style="background-color: {{ player.color }}"></div>
							<input type="radio" name="players_sequence" {% if player.pk == me.pk %}disabled{% endif %}>
						</label>
					{% if forloop.counter == 4 %}
					</div>
					<div class="btn-group radioBtnGroup btn-group-justified" data-toggle="buttons">
					{% endif %}
					{% endfor %}
					</div>
				</div>
			</div>
			<!-- <div id="zodiac_investigate" class="form-group row">
				<div class="btn-group btn-group-toggle" data-toggle="buttons">
					<ul>
						<li class="btn btn-light">
							<input type="radio" name="option{{ forloop.counter }}" id="option{{ forloop.counter }}" autocomplete="off">
							<img src="{{ zodiac.zodiac_image.image.url }}" alt="{{ zodiac.genuine }}" class="-avatar js-avatar-me">
						</li>
					</ul>
				</div>
			</div> -->
		</form>
	</main>
	<form id="fm" method="POST" action="">
		{% csrf_token %}
		<input type="hidden" class="form-control-plaintext" name="room_id" value="{{ room_id }}" required>
	</form>
	<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/cookie.js' %}"></script>
	<script type="text/javascript">
	String.prototype.format = function () {
		var args = arguments;
		return this.replace(/\{(\d+)\}/g, function (m, n) { return args[n]; });
	};
	$(function() {
		$("img").click(function() {
			console.log($(this).attr("alt"));
			if ($(this).attr("alt") === "True")
				$("#genuine").val("真");
			if ($(this).attr("alt") === "False")
				$("#genuine").val("伪");
		})
		setInterval(function() {
			$.ajaxSetup({
				beforeSend: function(xhr, settings) {
					if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
						xhr.setRequestHeader("X-CSRFToken", csrftoken);
					}
				}
			});
			$.ajax({
				url: "{% url 'MoA:GetNextPlay' %}",
				type: "POST",
				data: {
					"player_code": "{{ me.player_code }}",
					"room_id": "{{ room_id }}",
				},
				statusCode: {
					201: function(response) {
						// To-Do: dynamic generation
						// console.log(response);
						var start_speech = true;
						response.forEach(function(player) {
							if (player.fields.sequence < {{ me.sequence }}) {
								var label = $("label[data-color={0}]".format(player.fields.color))
								label.addClass("dim");
								label.children("input").prop('disabled', true);
							}
							else {
								if (player.fields.sequence > {{ me.sequence }})
									start_speech = false;
							}
						});
						$("#player_sequence").css("display", "");
						if (start_speech) {
							setTimeout(function() {
								$.ajax({
									url: "{% url 'MoA:StartBB' %}",
									type: "POST",
									data: {
										"room_id": "{{ room_id }}",
									},
									success: function(result) {
										// alert(result);
										$("#player_sequence").css("display", "none");
									}
								});
							}, 5000);
						}
					}
				}, success: function(result) {
					
				},
			});
		}, 3000);
		$("label.sequence").click(function() {
			// console.log($(this).data("color"));
			if (!$(this).prop('disabled')) {
				$.ajax({
					url: "{% url 'MoA:SetNextPlayer' %}",
					type: "POST",
					data: {
						"player_code": "{{ me.player_code }}",
						"color": $(this).data("color"),
					},
					success: function(result) {
						// alert(result);
						setTimeout(function() {
							$("#player_sequence").css("display", "none");
						}, 500);
					}
				});
			}
		});
	});
	</script>
</body>

</html>

apps/Helper/templates/home.html
{% extends "base.html" %}

{% block title %} Home {% endblock %} 

{% block content %}
		<div class="jumbotron">
			<h1>Helper App</h1>
			<p class="lead"></p>
			<a class="btn btn-lg btn-primary" href="{% url 'Helper:create_game' %}" role="button">创建游戏</a>
		</div>
{% endblock content %}

apps/Helper/templates/setup.html
{% extends "base.html" %}
{% block title %} SetupGame {% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
        <h4 class="mb-3">Input players</h4>
        <form id="fm" method="POST" action="{% url 'Helper:complete_setup_game' room_id %}" novalidate>
            {% csrf_token %}
            {% for number in numbers_of_players %}
            <div class="form-group row mb-4">
                <label for="player_name{{number}}" class="col-sm-3 col-form-label">Player {{number}}'s Name</label>
                <div class="col-sm-5">
                    <input type="text" class="form-control" id="player_name{{number}}" name="player_name{{number}}" placeholder="" value="Player {{number}} Name" required>
                    <div class="invalid-tooltip">
                        Player's name is required.
                    </div>
                </div>
                <div class="col-sm-4">
                    <select class="form-control d-block w-100" id="character_name{{number}}" name="character_name{{number}}" required>
                        <option value="">Choose...</option>
                        {% for character in characters %}
                        <option value="{{ character.value }}">{{ character.name }}</option>
                        {% endfor %}
                    </select>
                    <div class="invalid-tooltip">
                        Please choose a unique character.
                    </div>
                </div>
            </div>
            {% endfor %}
            <button class="btn btn-primary btn-lg btn-block" type="submit">Start Game</button>
        </form>
    </div>
</div>
{% endblock content %}
{% block javascripts %}
<script type="text/javascript">
function check_selects_duplicates() {
    var selects = document.getElementsByTagName('select');
    var values = [];
    var result = false;
    for (i = 0; i < selects.length; i++) {
        var select = selects[i];
        if (values.indexOf(select.value) > -1) {
        	select.setCustomValidity('invalid');
            result = true;
        }
        else {
        	select.setCustomValidity('');
            values.push(select.value);
        }
    }
    return result;
}
(function() {
    "use strict"
    window.addEventListener("load", function() {
        var form = document.getElementById("fm");
        form.addEventListener("submit", (function(event) {
            if (form.checkValidity() === false | check_selects_duplicates()) {
                event.preventDefault();
                event.stopPropagation();
            }
            form.classList.add("was-validated");
        }), false);
    });
})()
</script>
{% endblock javascripts %}